### ISSUE TITLE
如何使用torchcrf？

### ISSUE THREAD

**Issue by qhd1996** [hackerxiaobai/NER#1]
请问使用torchcrf定义crf层的时候，num_tag参数需要把开始和结束符都包括么？
例如有B-X I-X O标签，还需要加上两个start和end标签么

**Comment by hackerxiaobai** [comment]
> 请问使用torchcrf定义crf层的时候，num_tag参数需要把开始和结束符都包括么？
> 例如有B-X I-X O标签，还需要加上两个start和end标签么

+ 建议看官网
